/****** Object:  View [cons_reference].[dim_product_view]    Script Date: 12/4/2022 9:49:42 AM ******/
SET
  ANSI_NULLS ON
GO
SET
  QUOTED_IDENTIFIER ON
GO
  CREATE VIEW [cons_reference].[dim_product_view] AS
SELECT
  cast(description1 as varchar(100)) as Sku_Code,
  cast(description2 as varchar(500)) as Sku_Description,
  cast(dcs_code as varchar(20)) dcs_code,
  cast(dcs_name as varchar(30)) dcs_name,
  cast(merge_code as varchar(50)) merge_code,
  cast(merge_code_desc as varchar(300)) merge_code_desc,
  cast(active as int) active,
  cast(category as varchar(100)) category,
  cast(sub_category as varchar(100)) sub_category,
  cast(kit_category as varchar(100)) kit_category,
  cast(size as varchar(100)) size,
  cast(discontinuation_date as varchar(50)) discontinuation_date,
  cast(pack_size as int) pack_size,
  cast(EAN as varchar(100)) EAN,
  cast(sub_specific as varchar(10)) sub_specific,
  cast(write_off as int) write_off,
  cast(ss_only as int) ss_only,
  cast(keyI1 as varchar(10)) keyI1,
  cast(keyI2 as varchar(10)) keyI2,
  cast(keyI3 as varchar(100)) keyI3,
  cast(DG as int) DG,
  cast(pricelist_category as varchar(50)) pricelist_category,
  cast(pricelist_sub_category as varchar(50)) pricelist_sub_category,
  cast(base_sku as varchar(20)) base_sku,
  cast(product_type_cat as varchar(50)) product_type_cat,
  cast(product_type_sub_cat as varchar(50)) product_type_sub_cat,
  cast(status as varchar(50)) status,
  cast(item_class as varchar(50)) item_class,
  cast(item_sub_class as varchar(50)) item_sub_class,
  cast(last_updated_date as datetime) last_updated_date,
  cast(netsuite_id as bigint) netsuite_id,
  cast(is_lot_numbered as int) is_lot_numbered,
  cast(tmall_tax_code as varchar(10)) tmall_tax_code,
  cast(barcode_type as varchar(50)) barcode_type,
  cast(item_form as varchar(50)) item_form,
  cast(short_description as varchar(300)) short_description,
  cast(display_name as varchar(500)) display_name,
  cast(dg_class as varchar(20)) dg_class,
  cast(dg_packing_group as varchar(20)) dg_packing_group,
  cast(dg_un_number as varchar(20)) dg_un_number,
  cast(container as varchar(100)) container,
  cast(full_carton_weight as float) full_carton_weight,
  cast(inner_carton as int) inner_carton,
  cast(item_gross_weight as float) item_gross_weight,
  cast(item_net_weight as float) item_net_weight,
  cast(item_unit as varchar(10)) item_unit,
  cast(outer_carton as int) outer_carton,
  cast(packed_unit_volume as float) packed_unit_volume,
  cast(packed_unit_weight as float) packed_unit_weight,
  cast(product_depth as float) product_depth,
  cast(product_height as float) product_height,
  cast(product_width as float) product_width,
  cast(unit as int) unit,
  cast(export_pallet as int) export_pallet,
  cast(fda_code as varchar(30)) fda_code,
  cast(hs_code as varchar(50)) hs_code,
  cast(country_of_origin as varchar(50)) country_of_origin,
  cast(standard_pallet as int) standard_pallet,
  cast(voc_percentage as float) voc_percentage,
  cast(synced_from_ns as int) synced_from_ns,
  cast(commodity_code as varchar(150)) commodity_code,
  cast(shipper_width as float) shipper_width,
  cast(shipper_height as float) shipper_height,
  cast(shipper_depth as float) shipper_depth,
  cast(tax_schedule as varchar(100)) tax_schedule,
  cast(send_to_wms as varchar(10)) send_to_wms,
  cast(netsuite_updated_date as varchar(100)) netsuite_updated_date,
  cast(md_record_written_timestamp as datetime) md_record_written_timestamp,
  cast(md_record_written_pipeline_id as varchar(500)) md_record_written_pipeline_id,
  cast(md_transformation_job_id as int) md_transformation_job_id,
  cast(md_source_system as varchar(10)) md_source_system
FROM
  std.product_x;

GO