SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [stage].[sfmc_svoc]
(
	[contactkey] [nvarchar](max) NULL,
	[mobileConnectLocale] [nvarchar](max) NULL,
	[locale] [nvarchar](max) NULL,
	[globalCountry] [nvarchar](max) NULL,
	[globalLanguage] [nvarchar](max) NULL,
	[title] [nvarchar](max) NULL,
	[customer_group_id] [nvarchar](max) NULL,
	[last_surveyed] [nvarchar](max) NULL,
	[optinEmail] [nvarchar](max) NULL,
	[optinEmailLastUpdatedDate] [nvarchar](max) NULL,
	[emailBounceDate] [nvarchar](max) NULL,
	[EmailUnsubReason] [nvarchar](max) NULL,
	[optinMobile] [nvarchar](max) NULL,
	[optinMobileLastUpdatedDate] [nvarchar](max) NULL,
	[mobileBounceDate] [nvarchar](max) NULL,
	[pushOptin] [nvarchar](max) NULL,
	[pushOptinLastUpdatedDate] [nvarchar](max) NULL,
	[directMailOptin] [nvarchar](max) NULL,
	[directMailOptinLastUpdatedDate] [nvarchar](max) NULL,
	[telephoneMarketingOptin] [nvarchar](max) NULL,
	[telephoneMarketingOptinLastUpdatedDate] [nvarchar](max) NULL,
	[messagingAppOptin] [nvarchar](max) NULL,
	[messagingAppOptinLastUpdatedDate] [nvarchar](max) NULL,
	[consentToThirdPartyMarketing] [nvarchar](max) NULL,
	[ConsentToThirdPartyMarketingDate] [nvarchar](max) NULL,
	[consentToShareDataAbroad] [nvarchar](max) NULL,
	[ConsentToShareDataAbroadDate] [nvarchar](max) NULL,
	[accept_all_terms] [nvarchar](max) NULL,
	[created] [nvarchar](max) NULL,
	[source] [nvarchar](max) NULL,
	[SubscriptionType] [nvarchar](max) NULL,
	[onlineAccountFlag] [nvarchar](max) NULL,
	[onlineAccountcreateDate] [nvarchar](max) NULL,
	[first_purchase_channel] [nvarchar](max) NULL,
	[first_purchase_store] [nvarchar](max) NULL,
	[first_purchase_subsidiary] [nvarchar](max) NULL,
	[first_purchase_date] [nvarchar](max) NULL,
	[last_purchase_channel] [nvarchar](max) NULL,
	[last_purchase_store] [nvarchar](max) NULL,
	[last_purchase_subsidiary] [nvarchar](max) NULL,
	[last_purchase_date] [nvarchar](max) NULL,
	[lifetime_transactions] [nvarchar](max) NULL,
	[total_revenue_aud] [nvarchar](max) NULL,
	[most_purchased_subsidiary] [nvarchar](max) NULL,
	[second_purchase_date] [nvarchar](max) NULL,
	[random] [nvarchar](max) NULL,
	[RFV_Class] [nvarchar](max) NULL,
	[RFV_Segment_Name] [nvarchar](max) NULL,
	[EinsteinEmailEngagementPersona] [nvarchar](max) NULL,
	[InterestArray] [nvarchar](max) NULL,
	[Sent_180day] [nvarchar](max) NULL,
	[Unique_Opens_180day] [nvarchar](max) NULL,
	[Unique_Clicks_180day] [nvarchar](max) NULL,
	[Sent_90day] [nvarchar](max) NULL,
	[Unique_Opens_90day] [nvarchar](max) NULL,
	[Unique_Clicks_90day] [nvarchar](max) NULL,
	[Sent_30day] [nvarchar](max) NULL,
	[Unique_Opens_30day] [nvarchar](max) NULL,
	[Unique_Clicks_30day] [nvarchar](max) NULL,
	[sent_lifetime_count] [nvarchar](max) NULL,
	[open_lifetime_count] [nvarchar](max) NULL,
	[click_lifetime_count] [nvarchar](max) NULL,
	[Last_Email_Send_Date] [nvarchar](max) NULL,
	[Last_Email_Open_Date] [nvarchar](max) NULL,
	[Last_Email_Click_Date] [nvarchar](max) NULL,
	[Bronto_Open_Rate] [nvarchar](max) NULL,
	[Bronto_Click_Rate] [nvarchar](max) NULL,
	[Bronto_Last_Open_Date] [nvarchar](max) NULL,
	[Bronto_Last_Click_Date] [nvarchar](max) NULL,
	[Bronto_Status] [nvarchar](max) NULL,
	[first_txn_store_location_code] [nvarchar](max) NULL,
	[first_txn_store_name] [nvarchar](max) NULL,
	[md_record_ingestion_timestamp] [nvarchar](max) NULL,
	[md_record_ingestion_pipeline_id] [nvarchar](max) NULL,
	[md_source_system] [nvarchar](max) NULL,
	[skin_type] [nvarchar](max) NULL,
	[email] [nvarchar](max) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO