/****** Object:  StoredProcedure [std].[sp_ga_sessions_raw]    Script Date: 4/11/2022 5:05:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [std].[sp_ga_sessions_raw] @jobid [int],@step_number [int],@reset [varchar](10),@pipelineid [varchar](500) AS 

BEGIN
	BEGIN TRY
		IF @reset = 0
		BEGIN			
 


/*DELETE FROM TARGET IF DATA FOR THE DATES AVAILABLE IN STG IS ALREADY PRESENT, 
AND RELOAD DATES [AVAILABLE IN STG] TO STD*/

delete from [std].[ga_sessions_raw] 
where date in (select distinct date from [stage].[bq_ga_sessions_raw])

insert into [std].[ga_sessions_raw] 
select distinct
cast([VisitorId] as [varchar](200)) 	[VisitorId],
cast([visitNumber] as [bigint]) 	visitNumber,
cast([visitId] as [bigint]) 	visitId,
cast([visitStartTime] as [bigint]) 	visitStartTime,
cast([fullVisitorId] as [varchar](200)) 	fullVisitorId,
cast([userId] as [varchar](200)) 	userId,
cast([clientId] as [varchar](200)) 	clientId,
cast([date] as [varchar](200)) 	"date",
cast([visits] as [bigint]) 	visits,
cast([hits] as [bigint]) 	hits,
cast([pageviews] as [bigint]) 	pageviews,
cast([timeOnSite] as [bigint]) 	timeOnSite,
cast([bounces] as [bigint]) 	bounces,
cast([transactions] as [bigint]) 	transactions,
cast([transactionRevenue] as [bigint]) 	totals_transactionRevenue,
cast([newVisits] as [bigint]) 	newVisits,
cast([screenviews] as [bigint]) 	screenviews,
cast([uniqueScreenviews] as [bigint]) 	uniqueScreenviews,
cast([timeOnScreen] as [bigint]) 	timeOnScreen,
cast([totalTransactionRevenue] as [bigint]) 	totalTransactionRevenue,
cast([referralPath] as [varchar](4000)) 	referralPath,
cast([campaign] as [nvarchar](2500)) 	campaign,
cast([source] as [nvarchar](2500)) 	"source",
cast([medium] as [nvarchar](2500)) 	"medium",
cast([keyword] as [nvarchar](2500)) 	keyword,
cast([adContent] as [nvarchar](2500)) 	adContent,
cast([isTrueDirect] as [varchar] (10)) 	isTrueDirect,
cast([campaignCode] as [varchar](200)) 	campaignCode,
cast([browser] as [varchar](200)) 	browser,
cast([operatingSystem] as [varchar](200)) 	operatingSystem,
cast([language] as [varchar](200)) 	"language",
cast([screenResolution] as [varchar](200)) 	screenResolution,
cast([deviceCategory] as [varchar](200)) 	deviceCategory,
cast([continent] as [varchar](200)) 	continent,
cast([country] as [varchar](200)) 	country,
cast([region] as [varchar](200)) 	region,
cast([city] as [nvarchar](200)) 	city,
cast([cityId] as [varchar](200)) 	cityId,
cast([hitNumber] as [bigint]) 	hitNumber,
cast([time] as [bigint]) 	"time",
cast([type] as [varchar](200)) 	"type",
cast([hour] as [bigint]) 	"hour",
cast([minute] as [bigint]) 	"minute",
cast([isInteraction] as [varchar] (10)) 	isInteraction,
cast([isEntrance] as [varchar] (10)) 	isEntrance,
cast([isExit] as [varchar] (10)) 	isExit,
cast([referer] as [varchar](4000)) 	referer,
cast([pagePath] as [nvarchar](4000)) 	pagePath,
cast([hostname] as [varchar](200)) 	hostname,
cast([pageTitle] as [nvarchar](2500)) 	pageTitle,
cast([searchKeyword] as [nvarchar](2500)) 	searchKeyword,
cast([searchCategory] as [varchar](200)) 	searchCategory,
cast([pagePathLevel1] as [nvarchar](4000)) 	pagePathLevel1,
cast([pagePathLevel2] as [nvarchar](4000)) 	pagePathLevel2,
cast([pagePathLevel3] as [nvarchar](4000)) 	pagePathLevel3,
cast([pagePathLevel4] as [nvarchar](4000)) 	pagePathLevel4,
cast([transactionId] as [varchar](200)) 	transactionId,
cast([transactionRevenue_1] as [bigint]) 	hits_transactionRevenue,
cast([transactionTax] as [bigint]) 	transactionTax,
cast([transactionShipping] as [bigint]) 	transactionShipping,
cast([affiliation] as [varchar](200)) 	affiliation,
cast([currencyCode] as [varchar](200)) 	currencyCode,
cast([localTransactionRevenue] as [bigint]) 	localTransactionRevenue,
cast([localTransactionTax] as [bigint]) 	localTransactionTax,
cast([localTransactionShipping] as [bigint]) 	localTransactionShipping,
cast([transactionCoupon] as [varchar](200)) 	transactionCoupon,
cast([eventCategory] as [varchar](200)) 	eventCategory,
cast([eventAction] as [nvarchar](4000)) 	eventAction,
cast([eventLabel] as [nvarchar](2500)) 	eventLabel,
cast([action_type] as [varchar](200)) 	action_type,
cast([step] as [bigint]) 	step,
cast([option] as [nvarchar](200)) as	"option",
cast([socialInteractionNetwork] as [varchar](200)) 	socialInteractionNetwork,
cast([socialInteractionAction] as [varchar](200)) 	socialInteractionAction,
cast([socialInteractions] as [bigint]) 	socialInteractions,
cast([socialInteractionTarget] as [varchar](200)) 	socialInteractionTarget,
cast([socialNetwork] as [varchar](200)) 	socialNetwork,
cast([uniqueSocialInteractions] as [bigint]) 	uniqueSocialInteractions,
cast([hasSocialSourceReferral] as [varchar](200)) 	hasSocialSourceReferral,
cast([socialInteractionNetworkAction] as [varchar](200)) 	socialInteractionNetworkAction,
cast([pageLoadSample] as [bigint]) 	pageLoadSample,
cast([pageLoadTime] as [bigint]) 	pageLoadTime,
cast([dataSource] as [varchar](200)) 	dataSource,
cast([channelGrouping] as [varchar](200)) 	channelGrouping,
cast([socialEngagementType] as [varchar](200)) 	socialEngagementType,
cast([productSKU] as [varchar](200)) 	productSKU,
cast([v2ProductName] as [nvarchar](200)) 	v2ProductName,
cast([v2ProductCategory] as [varchar](200)) 	v2ProductCategory,
cast([productVariant] as [nvarchar](200)) 	productVariant,
cast([productBrand] as [varchar](200)) 	productBrand,
cast([productRevenue] as [bigint]) 	productRevenue,
cast([localProductRevenue] as [bigint]) 	localProductRevenue,
cast([productPrice] as [bigint]) 	productPrice,
cast([localProductPrice] as [bigint]) 	localProductPrice,
cast([productQuantity] as [bigint]) 	productQuantity,
cast([productRefundAmount] as [bigint]) 	productRefundAmount,
cast([localProductRefundAmount] as [bigint]) 	localProductRefundAmount,
cast([isImpression] as [varchar] (10)) 	isImpression,
cast([isClick] as [varchar] (10)) 	isClick,
cast([productListName] as [nvarchar](200)) 	productListName,
cast([productListPosition] as [bigint]) 	productListPosition,
cast([productCouponCode] as [varchar](200)) 	productCouponCode,
cast([contentGroup1] as [varchar](200)) 	contentGroup1,
cast([contentGroup2] as [varchar](200)) 	contentGroup2,
cast([contentGroup3] as [varchar](200)) 	contentGroup3,
cast([contentGroup4] as [varchar](200)) 	contentGroup4,
cast([contentGroup5] as [varchar](200)) 	contentGroup5,
cast([previousContentGroup1] as [varchar](200)) 	previousContentGroup1,
cast([previousContentGroup2] as [varchar](200)) 	previousContentGroup2,
cast([previousContentGroup3] as [varchar](200)) 	previousContentGroup3,
cast([previousContentGroup4] as [varchar](200)) 	previousContentGroup4,
cast([previousContentGroup5] as [varchar](200)) 	previousContentGroup5,
cast([contentGroupUniqueViews1] as [bigint]) 	contentGroupUniqueViews1,
cast([contentGroupUniqueViews2] as [bigint]) 	contentGroupUniqueViews2,
cast([contentGroupUniqueViews3] as [bigint]) 	contentGroupUniqueViews3,
cast([contentGroupUniqueViews4] as [bigint]) 	contentGroupUniqueViews4,
cast([contentGroupUniqueViews5] as [bigint]) 	contentGroupUniqueViews5,
cast([sessionQualityDim] as [bigint]) 	sessionQualityDim,
cast([subContinent] as [varchar](200)) 	subContinent,
cast([metro] as [varchar](200)) 	metro,
cast([domainLookupTime] as [bigint]) 	domainLookupTime,
cast([domContentLoadedTime] as [bigint]) 	domContentLoadedTime,
cast([domInteractiveTime] as [bigint]) 	domInteractiveTime,
cast([domLatencyMetricsSample] as [bigint]) 	domLatencyMetricsSample,
cast([pageDownloadTime] as [bigint]) 	pageDownloadTime,
cast([redirectionTime] as [bigint]) 	redirectionTime,
cast([serverConnectionTime] as [bigint]) 	serverConnectionTime,
cast([serverResponseTime] as [bigint]) 	serverResponseTime,
cast([speedMetricsSample] as [bigint]) 	speedMetricsSample,
cast([userTimingCategory] as [varchar](200)) 	userTimingCategory,
cast([userTimingLabel] as [varchar](200)) 	userTimingLabel,
cast([userTimingSample] as [bigint]) 	userTimingSample,
cast([userTimingValue] as [bigint]) 	userTimingValue,
cast([userTimingVariable] as [varchar](200)) 	userTimingVariable,
cast(experimentId as [varchar](200)) experimentId,
cast(experimentVariant as [varchar](200)) experimentVariant,
cast(promoCreative as [varchar](200) ) promoCreative ,
cast(promoId as  [varchar](200) ) promoId,
cast(promoName as [varchar](200)) promoName,
cast(promoPosition as [varchar](200)) promoPosition ,
cast(promoIsView as [varchar](10)) promoIsView ,
cast(promoIsClick as [varchar](10)) promoIsClick,
	cast([cd_1] as [varchar](200)) 	cd_1,
cast([cd_2] as [varchar](200)) 	cd_2,
cast([cd_3] as [varchar](200)) 	cd_3,
cast([cd_4] as [varchar](200)) 	cd_4,
cast([cd_5] as [varchar](200)) 	cd_5,
cast([cd_6] as [varchar](200)) 	cd_6,
cast([cd_7] as [varchar](200)) 	cd_7,
cast([cd_8] as [varchar](200)) 	cd_8,
cast([cd_9] as [varchar](200)) 	cd_9,
cast([cd_10] as [varchar](200)) 	cd_10,
cast([cd_11] as [nvarchar](200)) 	cd_11,
cast([cd_12] as [varchar](200)) 	cd_12,
cast([cd_13] as [varchar](200)) 	cd_13,
cast([cd_14] as [varchar](200)) 	cd_14,
cast([cd_15] as [varchar](200)) 	cd_15,
cast([cd_16] as [nvarchar](200)) 	cd_16,
cast([cd_17] as [varchar](200)) 	cd_17,
cast([cd_18] as [varchar](200)) 	cd_18,
cast([cd_19] as [varchar](200)) 	cd_19,
cast([cd_20] as [varchar](200)) 	cd_20,
cast([cd_21] as [varchar](200)) 	cd_21,
cast([cd_22] as [varchar](200)) 	cd_22,
cast([cd_23] as [varchar](200)) 	cd_23,
cast([cd_24] as [varchar](200)) 	cd_24,
cast([cd_25] as [nvarchar](200)) 	cd_25,
cast([cd_26] as [varchar](200)) 	cd_26,
cast([cd_27] as [varchar](200)) 	cd_27,
cast([cd_28] as [varchar](200)) 	cd_28,
cast([cd_29] as [varchar](200)) 	cd_29,
cast([cd_30] as [nvarchar](200)) 	cd_30,
cast([cd_31] as [varchar](200)) 	cd_31,
cast([cd_32] as [varchar](200)) 	cd_32,
cast([cd_33] as [varchar](200)) 	cd_33,
cast([cd_34] as [varchar](200)) cd_34,
cast([cd_35] as [varchar](200)) cd_35,
cast([cd_36] as [varchar](200)) cd_36,
cast([cd_37] as [varchar](200)) cd_37,
cast([cd_38] as [varchar](200)) cd_38,
cast([cd_39] as [varchar](200)) cd_39,
cast([cd_40] as [varchar](200)) cd_40,
cast([cd_41] as [varchar](200)) cd_41,
cast([cd_42] as [varchar](200)) cd_42,
cast([cd_43] as [varchar](200)) cd_43,
cast([cd_44] as [varchar](200)) cd_44,
cast([cd_45] as [varchar](200)) cd_45,
cast([cd_46] as [varchar](200)) cd_46,
cast([cd_47] as [varchar](200)) cd_47,
cast([cd_48] as [varchar](200)) cd_48,
cast([cd_49] as [varchar](200)) cd_49,
cast([cd_50] as [varchar](200)) cd_50,
cast([cd_51] as [varchar](200)) cd_51,
cast([cd_52] as [varchar](200)) cd_52,
cast([cd_53] as [varchar](200)) cd_53,
cast([cd_54] as [varchar](200)) cd_54,
cast([cd_55] as [varchar](200)) cd_55,
cast([cd_56] as [varchar](200)) cd_56,
cast([cd_57] as [varchar](200)) cd_57,
cast([cd_58] as [varchar](200)) cd_58,
cast([cd_59] as [varchar](200)) cd_59,
cast([cd_60] as [varchar](200)) cd_60,
cast([cd_61] as [varchar](200)) cd_61,
cast([cd_62] as [varchar](200)) cd_62,
cast([cd_63] as [varchar](200)) cd_63,
cast([cd_64] as [varchar](200)) cd_64,
cast([cd_65] as [varchar](200)) cd_65,
cast([cd_66] as [varchar](200)) cd_66,
cast([cd_67] as [varchar](200)) cd_67,
cast([cd_68] as [varchar](200)) cd_68,
cast([cd_69] as [varchar](200)) cd_69,
cast([cd_70] as [varchar](200)) cd_70,
cast([cd_71] as [varchar](200)) cd_71,
cast([cd_72] as [varchar](200)) cd_72,
cast([cd_73] as [varchar](200)) cd_73,
cast([cd_74] as [varchar](200)) cd_74,
cast([cd_75] as [varchar](200)) cd_75,
cast([cd_76] as [varchar](200)) cd_76,
cast([cd_77] as [varchar](200)) cd_77,
cast([cd_78] as [varchar](200)) cd_78,
cast([cd_79] as [varchar](200)) cd_79,
cast([cd_80] as [varchar](200)) cd_80,
cast([cd_81] as [varchar](200)) cd_81,
cast([cd_82] as [varchar](200)) cd_82,
cast([cd_83] as [varchar](200)) cd_83,
cast([cd_84] as [varchar](200)) cd_84,
cast([cd_85] as [varchar](200)) cd_85,
cast([cd_86] as [varchar](200)) cd_86,
cast([cd_87] as [varchar](200)) cd_87,
cast([cd_88] as [varchar](200)) cd_88,
cast([cd_89] as [varchar](200)) cd_89,
cast([cd_90] as [varchar](200)) cd_90,
cast([cd_91] as [varchar](200)) cd_91,
cast([cd_92] as [varchar](200)) cd_92,
cast([cd_93] as [varchar](200)) cd_93,
cast([cd_94] as [varchar](200)) cd_94,
cast([cd_95] as [varchar](200)) cd_95,
cast([cd_96] as [varchar](200)) cd_96,
cast([cd_97] as [varchar](200)) cd_97,
cast([cd_98] as [varchar](200)) cd_98,
cast([cd_99] as [varchar](200)) cd_99,
cast([cd_100] as [varchar](200)) cd_100,
CAST(CONVERT(DATETIME, [md_record_ingestion_timestamp], 103) AS DATETIME) AS [md_record_ingestion_timestamp],
cast([md_record_ingestion_pipeline_id] as [varchar](500)) 	md_record_ingestion_pipeline_id,
cast([md_source_system] as [varchar](200))	md_source_system,
getdate()  md_record_written_timestamp,
@pipelineid as 	md_record_written_pipeline_id,
@jobid as md_transformation_job_id
from 
[stage].[bq_ga_sessions_raw]

OPTION (LABEL = 'AADPSTDGASSN');

UPDATE STATISTICS [stage].[bq_ga_sessions_raw];

				--BELOW SCRIPT TO GET THE DRIVER TABLE READ COUNT AND TARGET TABLE WRITE COUNT
			DECLARE @label varchar(500)
			SET @label='AADPSTDGASSN'
			EXEC meta_ctl.sp_row_count @jobid,@step_number,@label
		END
		ELSE
		BEGIN
			DECLARE @newrec DATETIME, @onlydate DATE
			SELECT @newrec = max(md_record_written_timestamp) FROM std.ga_sessions_raw;
			SELECT @onlydate = CAST(@newrec AS DATE);
			
			DELETE FROM [std].[ga_sessions_raw] WHERE md_record_written_timestamp=@newrec;
		END
	END TRY

	BEGIN CATCH
		--ERROR OCCURED
		PRINT 'ERROR SECTION INSERT'

		INSERT meta_audit.transform_error_log_sp
		SELECT ERROR_NUMBER() AS ErrorNumber
			,ERROR_SEVERITY() AS ErrorSeverity
			,ERROR_STATE() AS ErrorState
			,'std.sp_ga_sessions_raw' AS ErrorProcedure
			,ERROR_MESSAGE() AS ErrorMessage
			,getdate() AS Updated_date
	END CATCH
END